### Script Generated by Control Surface Studio for Python 3 (resorted to default: no)
from .AudioSwift_Mixer import AudioSwift_Mixer

def create_instance(c_instance):
	return AudioSwift_Mixer(c_instance)
