### Script Generated by Control Surface Studio for Python 3 (resorted to default: no)
from .AudioSwift_Control import AudioSwift_Control

def create_instance(c_instance):
	return AudioSwift_Control(c_instance)
